name: Build NC Project GIS Pull v6
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: pyinstaller --noconfirm --clean --onefile --windowed --name NC_Project_GIS_Pull_v6 nc_project_gis_pull_v6.py
      - uses: actions/upload-artifact@v4
        with:
          name: NC_Project_GIS_Pull_v6_Windows
          path: dist/NC_Project_GIS_Pull_v6.exe
